FROM ubuntu:24.10
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root /home/runner/work/azure-cli-mcp/azure-cli-mcp/azure-cli-mcp-linux /work/azure-cli-mcp

USER 1001

CMD ["./azure-cli-mcp"]
